add a header and front page
Dancode-188/Daniel-Bitengo-portfolio pull request #1
Opened 2023-04-27 04:27 UTC by Dancode-188

-add index.html file
-add styles.css file
-add icons file
-add .gitignore file
-add node_modules file to .gitignore file
-add .stylelintrc.json
-add .hintrc
-add test.md
-add README.md
-add LICENSE.md

2023-04-27 06:16 UTC, shella12 requested changes
Hi @Dancode-188, 

Good job so far, indeed you have spent time on this project!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media1.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Highlights
- All linters passed ✅ 
- Professional README.md ✅   
- Correct use of git flow ✅ 

## Required Changes ♻️

- [ ] _Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-27 06:16 UTC, shella12 commented on styles.css
> +}
- [ ] Please make sure that your headings and paragraphs use the same fonts (family, weight, size) from the [figma design template](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?type=design&node-id=1-1471&t=j8nKhwkF2vm9Y7rv-0). (_hint: you need to import `Create Round`, `Poppins` and `Roboto`  from [google fonts](https://fonts.google.com/) and past it in your css file for it to be effective_)

| Figma design    | Your design |
| ------------- | ------------- |
|<img width="309" alt="Screenshot 2023-04-27 at 11 00 02 AM" src="https://user-images.githubusercontent.com/44798044/234772903-76cdde27-640d-417d-8d51-afd3ed70b2e9.png">|<img width="298" alt="Screenshot 2023-04-27 at 10 58 51 AM" src="https://user-images.githubusercontent.com/44798044/234773661-f092c54a-d137-4940-a940-d98cdd84cace.png">|


- [ ] Please make sure the layout (spacing) matches with the [figma design template](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?type=design&node-id=1-1471&t=j8nKhwkF2vm9Y7rv-0)

| Figma design    | Your design |
| ------------- | ------------- |
|<img width="309" alt="Screenshot 2023-04-27 at 11 00 02 AM" src="https://user-images.githubusercontent.com/44798044/234773973-c5380295-e2b4-4495-9743-d9016dd14293.png">|<img width="298" alt="Screenshot 2023-04-27 at 10 58 51 AM" src="https://user-images.githubusercontent.com/44798044/234774148-a4f1a72b-bf56-47e1-8a0a-4f96cc3ac676.png">|

2023-04-27 06:16 UTC, shella12 commented on index.html
> +        </div>
- [ ] Please use list tags (`ul` and `li`)to in-list the social media icons and inclose each icon into a hyperlink tag (`<a>`) . Apart from being semantically correct, the `a` tag will let you connect your social networks with the icons, using href.

2023-04-27 10:24 UTC, NahnahAJ requested changes
## Project Status: CHANGES REQUIRED :recycle: 
Hi <STUDENT_MENTION>, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which haven't been addressed yet.


 ## Highlights
- Good commit messages :heavy_check_mark: 
- Good use of the `.gitignore` file :heavy_check_mark: 
- Linters well setup and passing :heavy_check_mark: 
- Good use of GitHub flow :heavy_check_mark: 
- Professional Pull Request summary :heavy_check_mark: 
- Professional README :heavy_check_mark: 

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @NahnahAJ in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-27 10:24 UTC, NahnahAJ commented on index.html
> +                </div>
- [ ] Great job so far @Dancode-188 There are jsuta few changes you need to make and you'll be on your way to the next milestone :wink: 
- [ ] Just as the previous reviewer mentioned earlier, since this is your hamburger button, it should be enclosed in a (`nav` tag). The(`nav` tag) is for semantics reasons as it creates a clear semantic meaning for screen readers and other accessibility tools that this particular section is part of navigating. :100:

2023-04-27 10:24 UTC, NahnahAJ commented on index.html
> +    <section class="container">
- [ ] Just as the previous reviewer mentioned, in the Figma design, there is a background image that is currently missing in yours. But as per the project requirements, you should ensure that your design looks exactly like the Figma design. So kindly include the background image :100: 

| Your Design | Figma Design |
|--------|--------|
| ![image](https://user-images.githubusercontent.com/102699958/234833160-dc95fac8-8a6f-4933-9cf5-c7ca2727e516.png) | ![image](https://user-images.githubusercontent.com/102699958/234833009-07da49f0-7c99-4fca-a85e-d37c0bdd1f75.png) |

2023-04-27 10:24 UTC, NahnahAJ commented on index.html
> +        </div>
- [ ] Great job wrapping the social icons with anchor tags but as the previous reviewer also mentioned, it is important to use list tags `(ul and li) ` to semantically structure your social media icons. Please update your code to wrap each anchor tag containing the social media icon with a list item using the ` <li> `tag. This will help improve the readability and accessibility of your code. For example, your code can look something like this :+1: 

```
<div class="icon-container">
  <ul>
    <li><a href="#" target="_blank"><img src="icons/github.svg" class="github" alt="github-icon"></a></li>
    <li><a href="#" target="_blank"><img src="icons/linkedin.svg" class="linkedin" alt="linkedin-icon"></a></li>
    <li><a href="#" target="_blank"><img src="icons/angelist.svg" class="angelist" alt="angelist-icon"></a></li>
    <li><a href="#" target="_blank"><img src="icons/twitter.svg" class="twitter" alt="twitter-icon"></a></li>
    <li><a href="#" target="_blank"><img src="icons/medium.svg" class="medium" alt="medium-icon"></a></li>
  </ul>
</div>

```

2023-04-27 22:35 UTC, MaganaAsiati requested changes
# STATUS: Required Changes ♻️♻️♻️ 

Hi @Dancode-188 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![AlonzoLeroneThisCloseGIF](https://user-images.githubusercontent.com/50941074/161814298-b87179c3-315f-4207-ac3b-1d3e584d506e.gif)

## Highlights
✅ No linter error
✅ README is professional

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2023-04-27 22:35 UTC, MaganaAsiati commented on index.html
> +        </div>
- You did a great job by implementing the required changes from the previous reviewer by using a list  however it should be better to also make sure that the changes don't affect the design as you see in the picture below comes you miss arranged the disposition of icons please fix that to make your design stick to the figma design :+1: 

- Kindly you did also a Good job by adding the background image but make sure that you adjust it a bit in the write position to make you design much more to the figma design as required in the project :+1: 
## Your design 

![image](https://user-images.githubusercontent.com/95297251/235003002-225b7ac8-1335-49c9-8d0e-0347d8c6d494.png)

 ##Figma design

![](https://user-images.githubusercontent.com/102699958/234833009-07da49f0-7c99-4fca-a85e-d37c0bdd1f75.png)

2023-04-27 22:35 UTC, MaganaAsiati commented on index.html
> +                </div>
- [ OPTIONAL ] Kindly remove the text decoration to the logo to make it look like the figma design 

text-decoration-line: blink;

Your Design | Figma Design
-- | --
![](https://user-images.githubusercontent.com/102699958/234836406-1a109bb0-ee5a-4c59-98bc-6e761565ecac.png)  |  ![image](https://user-images.githubusercontent.com/95297251/235004892-f464f91c-0b4a-43ff-8e8c-1416bb59b16d.png)







 

<br class="Apple-interchange-newline">

2023-04-28 06:18 UTC, skyv26 approved these changes
Hi @Dancode-188 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![](https://media.giphy.com/media/3o6fIUZTTDl0IDjbZS/giphy.gif)

## Highlights
- Correct `GitHub` flow ✅ 
- UI looks good ✅ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @skyv26 in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-28 06:22 UTC, merged