add works and about section
Dancode-188/Daniel-Bitengo-portfolio pull request #2
Opened 2023-04-28 17:35 UTC by Dancode-188

-add background image
-add works section
-add about myself section

2023-04-28 20:18 UTC, Johnadibe requested changes
# STATUS: REQUIRED CHANGES ♻️
### Hi @Dancode-188👋🏽, 

Good job so far!👍
There are some issues that you still need to work on to go to the next project but you are almost there!☺

![mario_ladders](https://user-images.githubusercontent.com/20563252/121369265-4e418880-c901-11eb-848c-1eff06d5a4cf.gif)

## Highlights
✅ You used GitHub Flow correctly 👍🏽
✅ Linter checks passed✔️
✅ Used CSS Grid and Flexbox to layout element 👍🏽
✅ Professional README✔️


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

> - [ ] Please kindly ensure to write a very detailed PR summary. This allows other developers to understand what changes you implemented.👍

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-28 20:18 UTC, Johnadibe commented on styles.css
> +}
> - [ ] Based on the project requirements, Please kindly ensure to implement hover and pressed button state interactions. This is to improve the overall look and feel of your application.☺

2023-04-28 20:18 UTC, Johnadibe commented on index.html
> +                    </div>
- [ ] Please kindly ensure that the list of project technologies is a list `ul` and each of them a `li`.👍

2023-04-28 20:18 UTC, Johnadibe commented on index.html
> +            </div>
> - [ ] I suggest you wrap the technology categories ("Languages", "Frameworks" and "Skills") in a `ul` and each of them in a `li` and also wrap the technology in each category (e.g., "JavasScript", "HTML" and "CSS") in a list `ul` and each of them a `li`.
> ```
> <ul>
>   <li>Languages
>     <ul>
>       <li>JavaScript</li>
>       <li>Python</li>
>       <li>Java</li>
>     </ul>
>   </li>
> </ul>
> ```

> - [ ] Please kindly ensure to make your design stick to the Figma design as much as possible. This is to ensure a consistent and cohesive user experience.☺  
> 
> Figma design👇:

![1 - languages-match-figma](https://user-images.githubusercontent.com/40009354/235241462-df49bf70-5ae5-4c21-8a62-99627849fb6b.PNG)

 > Your design👇:

![1 - languages-not-match](https://user-images.githubusercontent.com/40009354/235241564-ec0e04fb-b5f0-4232-a856-57ffe41b026f.PNG)
>

2023-04-29 16:12 UTC, LionRouge1 reviewed
Hi @Dancode-188, 

Great work on making the changes 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![almost](https://media.giphy.com/media/R2m2NzVxQ3pbG/giphy.gif)

## Suggested changes :recycle: 

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

[OPTIONAL]
- [ ] Kindle make sure you use the same font (`font-family`) as the Figma design to show your ability to parse a Figma design to create a UI.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2023-04-29 16:12 UTC, LionRouge1 commented on index.html
> +                </div>
- [ ] Same here too, as pointed out earlier:point_up_2:

2023-04-29 16:12 UTC, LionRouge1 commented on index.html
> +        </div>
- [ ] Kindly note the shape that is before each category on the Figma design. It will be nice to add the same to your design to follow the Figma design. 

- [ ] And make sure you centre all the languages under each category to follow the Figma design.
### Your design :point_down: 
![Screenshot from 2023-04-29 16-05-05](https://user-images.githubusercontent.com/91142432/235312206-5982bca1-180e-46fd-be84-75795b722a58.png)

### Figma Design :point_down: 
![235241462-df49bf70-5ae5-4c21-8a62-99627849fb6b](https://user-images.githubusercontent.com/91142432/235312235-b6be45ea-de9a-441a-8d3d-1ca550a8817d.png)

2023-04-29 20:32 UTC, usorfaitheloho requested changes
Hi @Dancode-188 , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
- Good job implementing the figma design ✔️ 
- weldone following HTML and CSS best practices 💯 

 ## Required Changes ♻️

As suggested by the previous reviewer, kindly ensure that the list of each project technology is a `ul` list element with each of them in an `li` tag on `lines 80-84`, `lines 94-98` , `lines 108-112`, `lines 122-126`, `lines 136 -140`, and `lines 150-154`   
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-29 20:32 UTC, usorfaitheloho commented on styles.css
> +}
As suggested by the previous reviewer, please use the required figma styling for this line of `border: 1px solid #212121` 😄

2023-04-29 20:32 UTC, usorfaitheloho commented on index.html
> +              </div>
You did a good job adding the shape as requested by the previous reviewer, kindly center the languages as he also suggested 😄

2023-04-29 21:02 UTC, AdnanOlarmmi approved these changes
Hi @Dancode-188,

This is Adnan Is-haq, your beloved code reviewer, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![Approved office man](https://user-images.githubusercontent.com/41163571/219113922-5007d6bb-ff59-4916-b6d3-e5aad3cb4051.gif)

## Highlights
- Fixed changes.

## Optional suggestions
_Check the comments under the review._

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-29 21:27 UTC, merged